# Generated by Django 5.1.3 on 2024-11-26 09:33

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(validators=[home.models.validate_english]),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(validators=[home.models.validate_english]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, validators=[home.models.validate_english]),
        ),
    ]
